---
# NOTICE: As required by the Apache License v2.0, this notice is to state this file has been modified by Arachne Digital

# Specified host and port where THREAD will run
host: 0.0.0.0
port: 9999
# Either 'taxii-server' for latest data or 'local-json' to use local data (data from json_file)
taxii-local: taxii-server
# Either 'js-online-src' for fetching JS libraries online or 'js-local-src' to use locally saved JS libraries
js-libraries: js-online-src
# If you would like the database to be re-built on launch of THREAD
build: True
# The JSON file containing attack data; ensure file is in /models directory
json_file: enterprise-attack.json
